version: '3.8'

services:
  app:
    build: .
    ports:
      - "8080:8080"
    environment:
      - MQTT_BROKER=${MQTT_BROKER}
      - MQTT_USER=${MQTT_USER}
      - MQTT_PASSWORD=${MQTT_PASSWORD}
      - MQTT_SUBSCRIBE=${MQTT_SUBSCRIBE}
      - DB_HOST=${DB_HOST}
      - DB_PORT=${DB_PORT}
      - DB_NAME=${DB_NAME}
      - DB_USER=${DB_USER}
      - DB_PASSWORD=${DB_PASSWORD}
      - API_KEY=${API_KEY}
    depends_on:
      - db
      - mqtt

  db:
    image: postgres:13
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    ports:
      - "5432:5432"

  mqtt:
    image: MQTT_BROKER
    ports:
      - "1883:1883"
      - "9001:9001"

networks:
  default:
    name: scadanetwork
